### PR TITLE
Configured automated deploy with serverless framework and customized plugin

### PR DESCRIPTION
**Pull request by dnegometyanov**

### CODE REVIEW

**Comment by dnegometyanov** [comment]
Implemented all steps from the Task-2:

1. Manually created S3 bucket  and configured, was able to reach the app via S3 url

2.1 Manually created and configured CloudFront distribution. 
2.2 Invalidated CloudFront distribution. As the the result application became available via Cloundfront URL and got the 403 on the S3 Url.

3.1. Added small change to the title in index.html
3.2 Configured serverless framework, deployed it without custom commands from the plugin. It was needed to invalidate Cloudfront manually after that to get the updates on the Cloudfront Url.

4.1 Cleaned up S3, Cloudfront and also have to clean up CloudFormation as I had some not finished attempts and had the "delete failed" error.
4.2. Successfully deployed and invalidated caches with single command npm run cloudfront:update:build:deploy:nc

5. Again manually created a separate S3 bucket with different name to have the working link for point 2 of 2.1

Urls:

Cloudfront ( automated ): https://d106l6emub8p9j.cloudfront.net

Automated S3 that is linked to CloudFront: http://dnehometianov-shop-react-redux-cloudfront.s3-website-us-east-1.amazonaws.com/ (403 AccessDenied after it is configured via cloudfront)

Manually created in (5) S3, link to index.html https://dnehometianov-shop-react-redux-cloudfront-duplicate-for-s3.s3.amazonaws.com/index.html

**Comment by ansivgit** [comment]
Perfect job! Mark is 5

**Comment by DeepanshuGargEpam** [comment]
Your PR is reviewed from my End .
But there is one mistake which I found is when you create manual s3 url you don't have to add bucket policy in that you have to update policy through cloudfront and that url should be working only not s3 one. Please check.
Good Job! Mark is 5.

**Comment by dnegometyanov** [comment]
> Your PR is reviewed from my End .
> But there is one mistake which I found is when you create manual s3 url you don't have to add bucket policy in that you have to update policy through cloudfront and that url should be working only not s3 one. Please check.
> Good Job! Mark is 5.

yep, its already like you tell, everything is okay - cloudfront only is working, this one https://d106l6emub8p9j.cloudfront.net/

and the s3 is this one and its 403 http://dnehometianov-shop-react-redux-cloudfront.s3-website-us-east-1.amazonaws.com/

and I created in ANOTHER bucket the another S3 - so this one might confused you that S3 is working https://dnehometianov-shop-react-redux-cloudfront-duplicate-for-s3.s3.amazonaws.com/index.html

**Pull request merged**
